services:
  api-ecommerce-pg:
    image: bitnami/postgresql:latest
    container_name: api-ecommerce-pg
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/bitnami/postgresql

volumes:
  pg_data: